/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.crm.Frames.br;

import br.com.crm.businessobject.Produto;
import br.com.crm.businessobject.ProdutoSAC;
import br.com.crm.businessobject.ProdutoVenda;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wellweb
 */
public class Frame_Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Produtos
     */
    public Frame_Produtos() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        Produto p = new Produto();
        DefaultTableModel grid = (DefaultTableModel) tbProduto.getModel();

        while (grid.getRowCount() > 0) {
            grid.removeRow(0);
        }

        try {
            int i = 0;
            while (i < p.List().size()) {

                Produto pro = (Produto) p.List().get(i);


                grid.addRow(pro.carregarGrid());

                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_apple = new javax.swing.JLabel();
        jButton_MaisVendidos = new javax.swing.JButton();
        jButton_MaisComentados = new javax.swing.JButton();
        jButton_MaisReclamados = new javax.swing.JButton();
        jPanel_divisor_TOPO = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        jbl_fundo_black = new javax.swing.JLabel();
        jPanel_topo = new javax.swing.JPanel();
        jLabel_img_novo_user = new javax.swing.JLabel();
        jbl_Titulo = new javax.swing.JLabel();
        jButton_dispose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlb_apple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/apple.png"))); // NOI18N
        getContentPane().add(jlb_apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton_MaisVendidos.setBackground(new java.awt.Color(0, 153, 204));
        jButton_MaisVendidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_MaisVendidos.setForeground(new java.awt.Color(255, 255, 255));
        jButton_MaisVendidos.setText("MAIS VENDIDOS");
        jButton_MaisVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MaisVendidosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_MaisVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 40));

        jButton_MaisComentados.setBackground(new java.awt.Color(0, 153, 204));
        jButton_MaisComentados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_MaisComentados.setForeground(new java.awt.Color(255, 255, 255));
        jButton_MaisComentados.setText("MAIS COMENTADOS ");
        jButton_MaisComentados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MaisComentadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_MaisComentados, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 40));

        jButton_MaisReclamados.setBackground(new java.awt.Color(0, 153, 204));
        jButton_MaisReclamados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_MaisReclamados.setForeground(new java.awt.Color(255, 255, 255));
        jButton_MaisReclamados.setText("MAIS RECLAMADOS");
        jButton_MaisReclamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MaisReclamadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_MaisReclamados, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 200, 40));

        jPanel_divisor_TOPO.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_TOPO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_divisor_TOPOLayout = new javax.swing.GroupLayout(jPanel_divisor_TOPO);
        jPanel_divisor_TOPO.setLayout(jPanel_divisor_TOPOLayout);
        jPanel_divisor_TOPOLayout.setHorizontalGroup(
            jPanel_divisor_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        jPanel_divisor_TOPOLayout.setVerticalGroup(
            jPanel_divisor_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_divisor_TOPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, 10));

        tbProduto.setAutoCreateRowSorter(true);
        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "DESCRIÇÃO", "QUANTIDADE"
            }
        ));
        jScrollPane1.setViewportView(tbProduto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 580, 420));

        jbl_fundo_black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/fundo_pages_crm.jpg"))); // NOI18N
        getContentPane().add(jbl_fundo_black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jPanel_topo.setBackground(new java.awt.Color(0, 102, 204));
        jPanel_topo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_img_novo_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/user.png"))); // NOI18N

        jbl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbl_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jbl_Titulo.setText("RELACIONAMENTO DE PRODUTO");

        jButton_dispose.setBackground(new java.awt.Color(255, 0, 0));
        jButton_dispose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_dispose.setForeground(new java.awt.Color(255, 255, 255));
        jButton_dispose.setText("Fechar");
        jButton_dispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_disposeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_topoLayout = new javax.swing.GroupLayout(jPanel_topo);
        jPanel_topo.setLayout(jPanel_topoLayout);
        jPanel_topoLayout.setHorizontalGroup(
            jPanel_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_topoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_img_novo_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jbl_Titulo)
                .addGap(64, 64, 64)
                .addComponent(jButton_dispose)
                .addGap(20, 20, 20))
        );
        jPanel_topoLayout.setVerticalGroup(
            jPanel_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_topoLayout.createSequentialGroup()
                .addGroup(jPanel_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_img_novo_user)
                    .addGroup(jPanel_topoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbl_Titulo)
                            .addComponent(jButton_dispose))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_topo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_MaisVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MaisVendidosActionPerformed
        ProdutoVenda p = new ProdutoVenda();
        DefaultTableModel grid = (DefaultTableModel) tbProduto.getModel();
        
         List<ProdutoVenda> lista=new ArrayList();
       
        List<Integer> lista2 = new ArrayList();
        while (grid.getRowCount() > 0) {
            grid.removeRow(0);
        }

        try {
            int i = 0;
            while (i < p.List().size()) {
                       
                ProdutoVenda cli = (ProdutoVenda) p.List().get(i);
                

                grid.addRow(cli.carregarGrid());
                    
                i++;
            }
              i =0;
            
           while(i<lista.size()){
                lista2.set(i, lista.get(i).getQuantidade());
                i++;
            }
            
           while(i<lista.size()){
                lista2.set(i, lista.get(i).getQuantidade());
                i++;
            }
           
            
            ProdutoVenda.quickSort(lista2, 0, lista2.size());
            
            
            
          
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton_MaisVendidosActionPerformed

    private void jButton_MaisComentadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MaisComentadosActionPerformed
        ProdutoSAC p = new ProdutoSAC();
        DefaultTableModel grid = (DefaultTableModel) tbProduto.getModel();

        while (grid.getRowCount() > 0) {
            grid.removeRow(0);
        }

        try {
            int i = 0;
            while (i < p.List().size()) {

                ProdutoSAC cli = (ProdutoSAC) p.List().get(i);


                grid.addRow(cli.carregarGrid());

                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton_MaisComentadosActionPerformed

    private void jButton_MaisReclamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MaisReclamadosActionPerformed
        ProdutoSAC p = new ProdutoSAC();
        DefaultTableModel grid = (DefaultTableModel) tbProduto.getModel();

        while (grid.getRowCount() > 0) {
            grid.removeRow(0);
        }

        try {
            int i = 0;
            while (i < p.ListReclamacao().size()) {

                ProdutoSAC cli = (ProdutoSAC) p.ListReclamacao().get(i);


                grid.addRow(cli.carregarGrid());

                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton_MaisReclamadosActionPerformed

    private void jButton_disposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_disposeActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_disposeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_MaisComentados;
    private javax.swing.JButton jButton_MaisReclamados;
    private javax.swing.JButton jButton_MaisVendidos;
    private javax.swing.JButton jButton_dispose;
    private javax.swing.JLabel jLabel_img_novo_user;
    private javax.swing.JPanel jPanel_divisor_TOPO;
    private javax.swing.JPanel jPanel_topo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbl_Titulo;
    private javax.swing.JLabel jbl_fundo_black;
    private javax.swing.JLabel jlb_apple;
    private javax.swing.JTable tbProduto;
    // End of variables declaration//GEN-END:variables
}
