/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.crm.Frames.br;

import java.io.IOException;

/**
 *
 * @author JoiceGomes
 */
public class Frame_BI_BusinessIntelligence extends javax.swing.JFrame {

    /**
     * Creates new form Frame_BI_BusinessIntelligence
     */
    public Frame_BI_BusinessIntelligence() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Analyct = new javax.swing.JButton();
        jPanel_TOPO = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_dispose = new javax.swing.JButton();
        jPanel_divisor_TOPO = new javax.swing.JPanel();
        jLabel_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Analyct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/analytics_1.png"))); // NOI18N
        jButton_Analyct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnalyctActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Analyct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 600, 390));

        jPanel_TOPO.setBackground(new java.awt.Color(0, 102, 204));
        jPanel_TOPO.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Business Intelligence");

        jButton_dispose.setBackground(new java.awt.Color(255, 0, 0));
        jButton_dispose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_dispose.setForeground(new java.awt.Color(255, 255, 255));
        jButton_dispose.setText("Fechar");
        jButton_dispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_disposeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_TOPOLayout = new javax.swing.GroupLayout(jPanel_TOPO);
        jPanel_TOPO.setLayout(jPanel_TOPOLayout);
        jPanel_TOPOLayout.setHorizontalGroup(
            jPanel_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TOPOLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jButton_dispose)
                .addContainerGap())
        );
        jPanel_TOPOLayout.setVerticalGroup(
            jPanel_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TOPOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(jPanel_TOPOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_dispose)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_TOPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 61));

        jPanel_divisor_TOPO.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_TOPO.setBorder(new javax.swing.border.SoftBevelBorder(0));

        javax.swing.GroupLayout jPanel_divisor_TOPOLayout = new javax.swing.GroupLayout(jPanel_divisor_TOPO);
        jPanel_divisor_TOPO.setLayout(jPanel_divisor_TOPOLayout);
        jPanel_divisor_TOPOLayout.setHorizontalGroup(
            jPanel_divisor_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        jPanel_divisor_TOPOLayout.setVerticalGroup(
            jPanel_divisor_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_divisor_TOPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));

        jLabel_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/fundo_pages_crm.jpg"))); // NOI18N
        getContentPane().add(jLabel_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_disposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_disposeActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_disposeActionPerformed

    private void jButton_AnalyctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnalyctActionPerformed
        try {
Runtime.getRuntime().exec("cmd.exe /C start "
+ "https://analytics.google.com//");
} catch (IOException ex) {
System.out.println(ex.getMessage());
}
    }//GEN-LAST:event_jButton_AnalyctActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_BI_BusinessIntelligence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_BI_BusinessIntelligence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_BI_BusinessIntelligence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_BI_BusinessIntelligence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_BI_BusinessIntelligence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Analyct;
    private javax.swing.JButton jButton_dispose;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_back;
    private javax.swing.JPanel jPanel_TOPO;
    private javax.swing.JPanel jPanel_divisor_TOPO;
    // End of variables declaration//GEN-END:variables
}
