package br.com.crm.Frames.br;

import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wellweb
 */
public class FramesDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form Frames_DashBoard
     */
    public FramesDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_superior_blue = new javax.swing.JPanel();
        jPanel_divisor_preto = new javax.swing.JPanel();
        jLabel_icon_SOCIAL1 = new javax.swing.JLabel();
        jLabel_icon_SOCIAL = new javax.swing.JLabel();
        jLabel_icon_Estrategia = new javax.swing.JLabel();
        jLabel_icon_Relatorios = new javax.swing.JLabel();
        jLabel_icon_CALENDARIO = new javax.swing.JLabel();
        jLabel_icon_config = new javax.swing.JLabel();
        jLabel_icon_Clientes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton_icon_Clientes = new javax.swing.JButton();
        jButton_icon_Atualizacoes = new javax.swing.JButton();
        jButton_icon_Social = new javax.swing.JButton();
        jButton_icon_estrategia = new javax.swing.JButton();
        jButton_icon_relatorios = new javax.swing.JButton();
        jButton_icon_calendario = new javax.swing.JButton();
        jButton_Icon_config = new javax.swing.JButton();
        jTabbedPane_Dashboard_principal_com_guias = new javax.swing.JTabbedPane();
        jPanel_guia_dashboard_page_relatorios = new javax.swing.JPanel();
        jPanel_divisor_guia_relatorios = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton_on_guia_Relatorios_SAC = new javax.swing.JButton();
        jButton_on_guia_Relatorios_DESENP = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_img_relatorios_on_guia_relatorios = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_meses = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_mesReferencia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel_divisor_guia_marketing = new javax.swing.JPanel();
        jPanel_interno_guia_Marketing = new javax.swing.JPanel();
        jPanel_interno_guia_Marketing2 = new javax.swing.JPanel();
        jButton_Adword = new javax.swing.JButton();
        jLabel_img_marketing = new javax.swing.JLabel();
        jButton_Face = new javax.swing.JButton();
        jButton_buscape = new javax.swing.JButton();
        jButton_lomadee = new javax.swing.JButton();
        jButton_boobox = new javax.swing.JButton();
        jPanel_interno_guia_Marketing3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton_on_guia_Marketing_CampAtivas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_superior_blue.setBackground(new java.awt.Color(0, 153, 204));

        jPanel_divisor_preto.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_preto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_icon_SOCIAL1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_SOCIAL1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_SOCIAL1.setText("ATUALIZAÇÕES");

        jLabel_icon_SOCIAL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_SOCIAL.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_SOCIAL.setText("SOCIAL");

        jLabel_icon_Estrategia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_Estrategia.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_Estrategia.setText("ESTRATEGIA");

        jLabel_icon_Relatorios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_Relatorios.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_Relatorios.setText("RELATÓRIOS");

        jLabel_icon_CALENDARIO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_CALENDARIO.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_CALENDARIO.setText("PRODUTOS");

        jLabel_icon_config.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_config.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_config.setText("CONFIGURAÇÕES");

        jLabel_icon_Clientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_Clientes.setText("CLIENTES");

        javax.swing.GroupLayout jPanel_divisor_pretoLayout = new javax.swing.GroupLayout(jPanel_divisor_preto);
        jPanel_divisor_preto.setLayout(jPanel_divisor_pretoLayout);
        jPanel_divisor_pretoLayout.setHorizontalGroup(
            jPanel_divisor_pretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_divisor_pretoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel_icon_config)
                .addGap(44, 44, 44)
                .addComponent(jLabel_icon_CALENDARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel_icon_Relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel_icon_Estrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel_icon_SOCIAL)
                .addGap(78, 78, 78)
                .addComponent(jLabel_icon_SOCIAL1)
                .addGap(62, 62, 62)
                .addComponent(jLabel_icon_Clientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_divisor_pretoLayout.setVerticalGroup(
            jPanel_divisor_pretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_divisor_pretoLayout.createSequentialGroup()
                .addGroup(jPanel_divisor_pretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_icon_SOCIAL1)
                    .addComponent(jLabel_icon_SOCIAL)
                    .addComponent(jLabel_icon_Estrategia)
                    .addComponent(jLabel_icon_Relatorios)
                    .addComponent(jLabel_icon_CALENDARIO)
                    .addComponent(jLabel_icon_config)
                    .addComponent(jLabel_icon_Clientes))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/by_Eramus7-watermark.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        jButton_icon_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/users.png"))); // NOI18N
        jButton_icon_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_icon_ClientesActionPerformed(evt);
            }
        });

        jButton_icon_Atualizacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/refresh.png"))); // NOI18N
        jButton_icon_Atualizacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_icon_AtualizacoesActionPerformed(evt);
            }
        });

        jButton_icon_Social.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/monitor.png"))); // NOI18N

        jButton_icon_estrategia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/find.png"))); // NOI18N
        jButton_icon_estrategia.setPreferredSize(new java.awt.Dimension(89, 73));
        jButton_icon_estrategia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_icon_estrategiaActionPerformed(evt);
            }
        });

        jButton_icon_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/chart_up.png"))); // NOI18N

        jButton_icon_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/apple.png"))); // NOI18N
        jButton_icon_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_icon_calendarioActionPerformed(evt);
            }
        });

        jButton_Icon_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/tools_1.png"))); // NOI18N
        jButton_Icon_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Icon_configActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jButton_Icon_config, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_icon_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_icon_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton_icon_estrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_icon_Social, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton_icon_Atualizacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_icon_Clientes)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_icon_Clientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jButton_icon_Atualizacoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_icon_Social, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_Icon_config, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_icon_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jButton_icon_relatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton_icon_estrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_superior_blueLayout = new javax.swing.GroupLayout(jPanel_superior_blue);
        jPanel_superior_blue.setLayout(jPanel_superior_blueLayout);
        jPanel_superior_blueLayout.setHorizontalGroup(
            jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_divisor_preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_superior_blueLayout.setVerticalGroup(
            jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_divisor_preto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane_Dashboard_principal_com_guias.setBackground(new java.awt.Color(204, 255, 102));

        jPanel_guia_dashboard_page_relatorios.setBackground(new java.awt.Color(102, 102, 102));
        jPanel_guia_dashboard_page_relatorios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel_divisor_guia_relatorios.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_guia_relatorios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_divisor_guia_relatoriosLayout = new javax.swing.GroupLayout(jPanel_divisor_guia_relatorios);
        jPanel_divisor_guia_relatorios.setLayout(jPanel_divisor_guia_relatoriosLayout);
        jPanel_divisor_guia_relatoriosLayout.setHorizontalGroup(
            jPanel_divisor_guia_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_divisor_guia_relatoriosLayout.setVerticalGroup(
            jPanel_divisor_guia_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_on_guia_Relatorios_SAC.setBackground(new java.awt.Color(255, 255, 255));
        jButton_on_guia_Relatorios_SAC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_on_guia_Relatorios_SAC.setForeground(new java.awt.Color(102, 102, 102));
        jButton_on_guia_Relatorios_SAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/chart_up_1.png"))); // NOI18N
        jButton_on_guia_Relatorios_SAC.setText("Relatorios SAC");
        jButton_on_guia_Relatorios_SAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_on_guia_Relatorios_SACActionPerformed(evt);
            }
        });

        jButton_on_guia_Relatorios_DESENP.setBackground(new java.awt.Color(255, 255, 255));
        jButton_on_guia_Relatorios_DESENP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_on_guia_Relatorios_DESENP.setForeground(new java.awt.Color(102, 102, 102));
        jButton_on_guia_Relatorios_DESENP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/chart_up_1.png"))); // NOI18N
        jButton_on_guia_Relatorios_DESENP.setText("Relatorio de Desempenho");
        jButton_on_guia_Relatorios_DESENP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_on_guia_Relatorios_DESENPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton_on_guia_Relatorios_DESENP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_on_guia_Relatorios_SAC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_on_guia_Relatorios_SAC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton_on_guia_Relatorios_DESENP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");

        jLabel_img_relatorios_on_guia_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/relatorios_dash.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("GERAR RELATÓRIO");

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("EXPORTAR");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VENDAS", "CLIENTES", "CONVERÇÃO", "CAPTAÇÃO", "RECLAMAÇÕES", "SOLUÇÕES", "SUGESTÕES", "MIDIA SOCIAL" }));

        jLabel5.setText("Tipo de Relatório :");

        jComboBox_meses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox_meses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_mesesActionPerformed(evt);
            }
        });

        jLabel4.setText("Alterar Mês : ");

        jLabel1.setText("MÊS DE REFERENCIA");

        jLabel_mesReferencia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_mesReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_meses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(jLabel_img_relatorios_on_guia_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_img_relatorios_on_guia_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_mesReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_guia_dashboard_page_relatoriosLayout = new javax.swing.GroupLayout(jPanel_guia_dashboard_page_relatorios);
        jPanel_guia_dashboard_page_relatorios.setLayout(jPanel_guia_dashboard_page_relatoriosLayout);
        jPanel_guia_dashboard_page_relatoriosLayout.setHorizontalGroup(
            jPanel_guia_dashboard_page_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_divisor_guia_relatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_guia_dashboard_page_relatoriosLayout.setVerticalGroup(
            jPanel_guia_dashboard_page_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_guia_dashboard_page_relatoriosLayout.createSequentialGroup()
                .addComponent(jPanel_divisor_guia_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane_Dashboard_principal_com_guias.addTab("Relatórios", jPanel_guia_dashboard_page_relatorios);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jPanel_divisor_guia_marketing.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_guia_marketing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_divisor_guia_marketingLayout = new javax.swing.GroupLayout(jPanel_divisor_guia_marketing);
        jPanel_divisor_guia_marketing.setLayout(jPanel_divisor_guia_marketingLayout);
        jPanel_divisor_guia_marketingLayout.setHorizontalGroup(
            jPanel_divisor_guia_marketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_divisor_guia_marketingLayout.setVerticalGroup(
            jPanel_divisor_guia_marketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel_interno_guia_Marketing.setBackground(new java.awt.Color(0, 153, 204));
        jPanel_interno_guia_Marketing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_interno_guia_MarketingLayout = new javax.swing.GroupLayout(jPanel_interno_guia_Marketing);
        jPanel_interno_guia_Marketing.setLayout(jPanel_interno_guia_MarketingLayout);
        jPanel_interno_guia_MarketingLayout.setHorizontalGroup(
            jPanel_interno_guia_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_interno_guia_MarketingLayout.setVerticalGroup(
            jPanel_interno_guia_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel_interno_guia_Marketing2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel_interno_guia_Marketing2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Adword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/ico-adwords.png"))); // NOI18N
        jButton_Adword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdwordActionPerformed(evt);
            }
        });

        jLabel_img_marketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/marketing.png"))); // NOI18N

        jButton_Face.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/ico-face.png"))); // NOI18N
        jButton_Face.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FaceActionPerformed(evt);
            }
        });

        jButton_buscape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/ico-buscape.png"))); // NOI18N
        jButton_buscape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscapeActionPerformed(evt);
            }
        });

        jButton_lomadee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/ico-lomadee.png"))); // NOI18N
        jButton_lomadee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lomadeeActionPerformed(evt);
            }
        });

        jButton_boobox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/ico-boobox.png"))); // NOI18N
        jButton_boobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_booboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_interno_guia_Marketing2Layout = new javax.swing.GroupLayout(jPanel_interno_guia_Marketing2);
        jPanel_interno_guia_Marketing2.setLayout(jPanel_interno_guia_Marketing2Layout);
        jPanel_interno_guia_Marketing2Layout.setHorizontalGroup(
            jPanel_interno_guia_Marketing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_interno_guia_Marketing2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_interno_guia_Marketing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_interno_guia_Marketing2Layout.createSequentialGroup()
                        .addComponent(jButton_Adword, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Face, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_interno_guia_Marketing2Layout.createSequentialGroup()
                        .addComponent(jButton_buscape)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_lomadee, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_boobox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addComponent(jLabel_img_marketing)
                .addContainerGap())
        );
        jPanel_interno_guia_Marketing2Layout.setVerticalGroup(
            jPanel_interno_guia_Marketing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_interno_guia_Marketing2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_interno_guia_Marketing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_img_marketing)
                    .addGroup(jPanel_interno_guia_Marketing2Layout.createSequentialGroup()
                        .addGroup(jPanel_interno_guia_Marketing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Adword, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jButton_Face, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_boobox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_interno_guia_Marketing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_buscape, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jButton_lomadee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel_interno_guia_Marketing3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel_interno_guia_Marketing3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_interno_guia_Marketing3Layout = new javax.swing.GroupLayout(jPanel_interno_guia_Marketing3);
        jPanel_interno_guia_Marketing3.setLayout(jPanel_interno_guia_Marketing3Layout);
        jPanel_interno_guia_Marketing3Layout.setHorizontalGroup(
            jPanel_interno_guia_Marketing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_interno_guia_Marketing3Layout.setVerticalGroup(
            jPanel_interno_guia_Marketing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_on_guia_Marketing_CampAtivas.setBackground(new java.awt.Color(255, 255, 255));
        jButton_on_guia_Marketing_CampAtivas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_on_guia_Marketing_CampAtivas.setForeground(new java.awt.Color(102, 102, 102));
        jButton_on_guia_Marketing_CampAtivas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/chart_up_1.png"))); // NOI18N
        jButton_on_guia_Marketing_CampAtivas.setText("Campanhas Ativas");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton_on_guia_Marketing_CampAtivas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton_on_guia_Marketing_CampAtivas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_divisor_guia_marketing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel_interno_guia_Marketing3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel_interno_guia_Marketing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_interno_guia_Marketing2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel_divisor_guia_marketing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_interno_guia_Marketing2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_interno_guia_Marketing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(479, 479, 479)
                .addComponent(jPanel_interno_guia_Marketing3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane_Dashboard_principal_com_guias.addTab("Marketing", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_superior_blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane_Dashboard_principal_com_guias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel_superior_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane_Dashboard_principal_com_guias, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_icon_calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_icon_calendarioActionPerformed
     Frame_Produtos frm = new Frame_Produtos();
     frm.setVisible(true);
    }//GEN-LAST:event_jButton_icon_calendarioActionPerformed

    private void jButton_on_guia_Relatorios_SACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_on_guia_Relatorios_SACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_on_guia_Relatorios_SACActionPerformed

    private void jComboBox_mesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_mesesActionPerformed
        jLabel_mesReferencia.setText(""+jComboBox_meses.getSelectedItem());
    }//GEN-LAST:event_jComboBox_mesesActionPerformed

    private void jButton_icon_AtualizacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_icon_AtualizacoesActionPerformed
      new Frame_Atualizacoes().setVisible(true);
    }//GEN-LAST:event_jButton_icon_AtualizacoesActionPerformed

    private void jButton_icon_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_icon_ClientesActionPerformed
     new  Frame_Listar_Rank_Clientes().setVisible(true);
    }//GEN-LAST:event_jButton_icon_ClientesActionPerformed

    private void jButton_on_guia_Relatorios_DESENPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_on_guia_Relatorios_DESENPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_on_guia_Relatorios_DESENPActionPerformed

    private void jButton_AdwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdwordActionPerformed
        try {
Runtime.getRuntime().exec("cmd.exe /C start "
+ "https://www.google.com.br/adwords");
} catch (IOException ex) {
System.out.println(ex.getMessage());
}
    }//GEN-LAST:event_jButton_AdwordActionPerformed

    private void jButton_Icon_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Icon_configActionPerformed
       new FrameAlterarSenha().setVisible(true);
    }//GEN-LAST:event_jButton_Icon_configActionPerformed

    private void jButton_FaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FaceActionPerformed
        try {
Runtime.getRuntime().exec("cmd.exe /C start "
+ "https://www.facebook.com/");
} catch (IOException ex) {
System.out.println(ex.getMessage());
}
    }//GEN-LAST:event_jButton_FaceActionPerformed

    private void jButton_buscapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscapeActionPerformed
        try {
Runtime.getRuntime().exec("cmd.exe /C start "
+ "https://www.buscape.com/");
} catch (IOException ex) {
System.out.println(ex.getMessage());
}
    }//GEN-LAST:event_jButton_buscapeActionPerformed

    private void jButton_lomadeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lomadeeActionPerformed
        try {
Runtime.getRuntime().exec("cmd.exe /C start "
+ "http://br.lomadee.com/");
} catch (IOException ex) {
System.out.println(ex.getMessage());
}
    }//GEN-LAST:event_jButton_lomadeeActionPerformed

    private void jButton_icon_estrategiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_icon_estrategiaActionPerformed
      new Frame_BI_BusinessIntelligence().setVisible(true);
    }//GEN-LAST:event_jButton_icon_estrategiaActionPerformed

    private void jButton_booboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_booboxActionPerformed
try {
Runtime.getRuntime().exec("cmd.exe /C start "
+ "http://boobox.com/");
} catch (IOException ex) {
System.out.println(ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_booboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramesDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramesDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramesDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramesDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramesDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Adword;
    private javax.swing.JButton jButton_Face;
    private javax.swing.JButton jButton_Icon_config;
    private javax.swing.JButton jButton_boobox;
    private javax.swing.JButton jButton_buscape;
    private javax.swing.JButton jButton_icon_Atualizacoes;
    private javax.swing.JButton jButton_icon_Clientes;
    private javax.swing.JButton jButton_icon_Social;
    private javax.swing.JButton jButton_icon_calendario;
    private javax.swing.JButton jButton_icon_estrategia;
    private javax.swing.JButton jButton_icon_relatorios;
    private javax.swing.JButton jButton_lomadee;
    private javax.swing.JButton jButton_on_guia_Marketing_CampAtivas;
    private javax.swing.JButton jButton_on_guia_Relatorios_DESENP;
    private javax.swing.JButton jButton_on_guia_Relatorios_SAC;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox_meses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_icon_CALENDARIO;
    private javax.swing.JLabel jLabel_icon_Clientes;
    private javax.swing.JLabel jLabel_icon_Estrategia;
    private javax.swing.JLabel jLabel_icon_Relatorios;
    private javax.swing.JLabel jLabel_icon_SOCIAL;
    private javax.swing.JLabel jLabel_icon_SOCIAL1;
    private javax.swing.JLabel jLabel_icon_config;
    private javax.swing.JLabel jLabel_img_marketing;
    private javax.swing.JLabel jLabel_img_relatorios_on_guia_relatorios;
    private javax.swing.JLabel jLabel_mesReferencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_divisor_guia_marketing;
    private javax.swing.JPanel jPanel_divisor_guia_relatorios;
    private javax.swing.JPanel jPanel_divisor_preto;
    private javax.swing.JPanel jPanel_guia_dashboard_page_relatorios;
    private javax.swing.JPanel jPanel_interno_guia_Marketing;
    private javax.swing.JPanel jPanel_interno_guia_Marketing2;
    private javax.swing.JPanel jPanel_interno_guia_Marketing3;
    private javax.swing.JPanel jPanel_superior_blue;
    private javax.swing.JTabbedPane jTabbedPane_Dashboard_principal_com_guias;
    // End of variables declaration//GEN-END:variables
}
