/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.crm.Frames.br;

import br.com.crm.businessobject.Usuario;
import br.com.crm.datalayer.UsuarioDao;
import javax.swing.JOptionPane;

/**
 *
 * @author wellweb
 */
public class FrameAlterarSenha extends javax.swing.JFrame {

    /**
     * Creates new form Frame_cadastro_Usuarios
     */
    public FrameAlterarSenha() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblErro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_cpf = new javax.swing.JLabel();
        jLabel_nome1 = new javax.swing.JLabel();
        txtSenhaAtual = new javax.swing.JPasswordField();
        txtNovaSenha = new javax.swing.JPasswordField();
        txtNovaSenhaConfirmar = new javax.swing.JPasswordField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblErro = new javax.swing.JLabel();
        jbl_fundo_black = new javax.swing.JLabel();
        jLabel_img_novo_user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/unlock.png"))); // NOI18N
        jLabel2.setText("ALTERAR SENHA");

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 580, 54));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONFIRMAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 307, 50));

        jLabel_nome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nome.setText("NOVA SENHA:");
        getContentPane().add(jLabel_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jLabel_cpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cpf.setText("SENHA ATUAL:");
        getContentPane().add(jLabel_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel_nome1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_nome1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nome1.setText("NOVA SENHA:");
        getContentPane().add(jLabel_nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));
        getContentPane().add(txtSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 330, -1));
        getContentPane().add(txtNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 330, -1));
        getContentPane().add(txtNovaSenhaConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 330, -1));

        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("USUÁRIO:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 330, -1));

        lblErro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblErro.setForeground(new java.awt.Color(255, 255, 255));
        lblErro.setText("SENHAS NAO COMPATÍVEIS");
        getContentPane().add(lblErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        jbl_fundo_black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/fundo_pages_crm.jpg"))); // NOI18N
        getContentPane().add(jbl_fundo_black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel_img_novo_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/user.png"))); // NOI18N
        getContentPane().add(jLabel_img_novo_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Usuario usu = new Usuario();
        
        
        
            
            try{  
                int idFunc = Integer.parseInt(txtUsuario.getText());
                String senhaAtual= new String (txtSenhaAtual.getPassword());
                String senhaNova1= new String (txtNovaSenha.getPassword());
                String senhaNova2= new String (txtNovaSenhaConfirmar.getPassword());
                
                if (senhaAtual.isEmpty() == false && senhaNova1.isEmpty() == false && senhaNova2.isEmpty() == false && idFunc != 0){                   
                    
                    if(usu.mudarSenha(idFunc, senhaAtual, senhaNova1)){                        
                        JOptionPane.showMessageDialog(this, "SENHA ALTERADA COM SUCESSO");
                        this.dispose();
                    }
                    else {
                        lblErro.setVisible(true);
                    }
                }                             
                else{
                    throw new Exception("CAMPOS NÃO PREENCHIDOS");
                }
                
            }
            
            catch (Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
            
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAlterarSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JLabel jLabel_img_novo_user;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_nome1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jbl_fundo_black;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtNovaSenha;
    private javax.swing.JPasswordField txtNovaSenhaConfirmar;
    private javax.swing.JPasswordField txtSenhaAtual;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
