/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.crm.Frames.br;

import br.com.crm.businessobject.Cliente;
import java.text.Format;
import java.text.SimpleDateFormat;

/**
 *
 * @author Vinícius
 */
public class FrameMaisDetalhes extends javax.swing.JFrame {
    
    Cliente cli = new Cliente();
    
    
    /**
     * Creates new form FrameMaisDetalhes
     */
    public FrameMaisDetalhes() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        jLabel_nome1 = new javax.swing.JLabel();
        jLabel_nome = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_img_novo_user = new javax.swing.JLabel();
        jPanel_divisor_TOPO = new javax.swing.JPanel();
        lblUsuario1 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        lblUsuario3 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtClassificacao = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        lblUsuario4 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Mais detalhes Cliente"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(0, 102, 204));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 440, 50));

        jLabel_nome1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nome1.setText("NOME:");
        getContentPane().add(jLabel_nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel_nome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nome.setText("CPF:");
        getContentPane().add(jLabel_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("SEXO:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        txtNome.setEditable(false);
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 440, 30));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAIS INFORMAÇÕES");

        jLabel_img_novo_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_img_novo_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_img_novo_user)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 61));

        jPanel_divisor_TOPO.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_TOPO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_divisor_TOPOLayout = new javax.swing.GroupLayout(jPanel_divisor_TOPO);
        jPanel_divisor_TOPO.setLayout(jPanel_divisor_TOPOLayout);
        jPanel_divisor_TOPOLayout.setHorizontalGroup(
            jPanel_divisor_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        jPanel_divisor_TOPOLayout.setVerticalGroup(
            jPanel_divisor_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_divisor_TOPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));

        lblUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario1.setText("EMAIL:");
        getContentPane().add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        lblUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario2.setText("CLASSIFICAÇÃO:");
        getContentPane().add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        lblUsuario3.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario3.setText("TELEFONE:");
        getContentPane().add(lblUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        txtCPF.setEditable(false);
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 230, 30));

        txtSexo.setEditable(false);
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 140, -1));

        txtEmail.setEditable(false);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 440, 30));

        txtClassificacao.setEditable(false);
        getContentPane().add(txtClassificacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 135, -1));

        txtTelefone.setEditable(false);
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 230, 30));

        lblUsuario4.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario4.setText("DATA DE NASCIMENTO:");
        getContentPane().add(lblUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        txtData.setEditable(false);
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 135, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/fundo_pages_crm.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_btnVoltarActionPerformed
    
    public FrameMaisDetalhes(Cliente usu){               
        initComponents();
        
        Format formatter = new SimpleDateFormat("dd-MM-yyyy");
        
        
        cli = usu;
        txtNome.setText(cli.getNome());
        txtCPF.setText(cli.getCPF());        
        txtSexo.setText(String.valueOf(cli.getSexo()));
        txtEmail.setText(cli.getEmail());
        txtClassificacao.setText(cli.getClassificacao());
        txtTelefone.setText(cli.getTelefone());
        txtData.setText(formatter.format(usu.getDataNascimento()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMaisDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMaisDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMaisDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMaisDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMaisDetalhes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_img_novo_user;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_nome1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_divisor_TOPO;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtClassificacao;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
