/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.crm.Frames.br;

import br.com.crm.businessobject.Cliente;
import br.com.crm.businessobject.Venda;
import br.com.crm.datalayer.ClienteDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wellweb
 */
public class Frame_Listar_Rank_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Listar_Rank_Clientes
     */
    public Frame_Listar_Rank_Clientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_divisor_TOPO = new javax.swing.JPanel();
        jTabbedPane_RankClientes = new javax.swing.JTabbedPane();
        jPanel_guia_MelhoresClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMelhoresClientes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnAumentar = new javax.swing.JButton();
        btnDiminuir = new javax.swing.JButton();
        btnMaisDetalhes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMaisCompras = new javax.swing.JTable();
        jButton_MAIS_DETALHES_MES1 = new javax.swing.JButton();
        jButton_Alterar_nivel_mes1 = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/users.png"))); // NOI18N
        jLabel2.setText("RANK MELHORES CLIENTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel2)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        jPanel_divisor_TOPO.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_TOPO.setBorder(new javax.swing.border.SoftBevelBorder(0));

        javax.swing.GroupLayout jPanel_divisor_TOPOLayout = new javax.swing.GroupLayout(jPanel_divisor_TOPO);
        jPanel_divisor_TOPO.setLayout(jPanel_divisor_TOPOLayout);
        jPanel_divisor_TOPOLayout.setHorizontalGroup(
            jPanel_divisor_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        jPanel_divisor_TOPOLayout.setVerticalGroup(
            jPanel_divisor_TOPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_divisor_TOPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, -1));

        jTabbedPane_RankClientes.setBackground(new java.awt.Color(153, 153, 153));

        jPanel_guia_MelhoresClientes.setBackground(new java.awt.Color(153, 153, 153));

        tbMelhoresClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), new java.awt.Color(102, 102, 102)));
        tbMelhoresClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CPF", "CLASSIFICAÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMelhoresClientes);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAumentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/rank_icon_medalha.png"))); // NOI18N
        btnAumentar.setText("AUMENTAR CLASSIFICAÇÃO");
        btnAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarActionPerformed(evt);
            }
        });

        btnDiminuir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/rank_icon_medalha.png"))); // NOI18N
        btnDiminuir.setText("DIMINUIR CLASSIFICAÇÃO");
        btnDiminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiminuirActionPerformed(evt);
            }
        });

        btnMaisDetalhes.setText("MAIS DETALHES");
        btnMaisDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_guia_MelhoresClientesLayout = new javax.swing.GroupLayout(jPanel_guia_MelhoresClientes);
        jPanel_guia_MelhoresClientes.setLayout(jPanel_guia_MelhoresClientesLayout);
        jPanel_guia_MelhoresClientesLayout.setHorizontalGroup(
            jPanel_guia_MelhoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_guia_MelhoresClientesLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_guia_MelhoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDiminuir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAumentar, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaisDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_guia_MelhoresClientesLayout.setVerticalGroup(
            jPanel_guia_MelhoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_guia_MelhoresClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDiminuir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnMaisDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        jTabbedPane_RankClientes.addTab("Melhores Clientes", jPanel_guia_MelhoresClientes);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        tbMaisCompras.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 51), new java.awt.Color(102, 102, 102)));
        tbMaisCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD CLIENTE", "NOME", "CPF", "QTD COMPRAS", "CLASSIFICAÇÃO"
            }
        ));
        jScrollPane3.setViewportView(tbMaisCompras);

        jButton_MAIS_DETALHES_MES1.setText("MAIS DETALHES");
        jButton_MAIS_DETALHES_MES1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MAIS_DETALHES_MES1ActionPerformed(evt);
            }
        });

        jButton_Alterar_nivel_mes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/find_1.png"))); // NOI18N
        jButton_Alterar_nivel_mes1.setText("HISTÓRICO DE COMPRAS");
        jButton_Alterar_nivel_mes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Alterar_nivel_mes1ActionPerformed(evt);
            }
        });

        btnBuscar1.setText("BUSCAR");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Alterar_nivel_mes1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jButton_MAIS_DETALHES_MES1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(btnBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_MAIS_DETALHES_MES1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Alterar_nivel_mes1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        jTabbedPane_RankClientes.addTab("Com Mais Compras", jPanel1);

        getContentPane().add(jTabbedPane_RankClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 950, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaisDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisDetalhesActionPerformed
        Cliente c = new Cliente();
        Cliente cli = new Cliente();
        int selecionada = tbMelhoresClientes.getSelectedRow();

        if (selecionada != -1) {

            String cpf = tbMelhoresClientes.getValueAt(selecionada, 1).toString();

            try {
                cli = c.findCliente(cpf);

                FrameMaisDetalhes frame = new FrameMaisDetalhes(cli);
                frame.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnMaisDetalhesActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Cliente c = new Cliente();
        DefaultTableModel grid = (DefaultTableModel) tbMelhoresClientes.getModel();

        while (grid.getRowCount() > 0) {
            grid.removeRow(0);
        }

        try {
            int i = 0;
            while (i < c.List().size()) {
                Cliente cli = (Cliente) c.List().get(i);

                grid.addRow(cli.carregarGrid());

                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        Cliente c = new Cliente();
        DefaultTableModel grid = (DefaultTableModel) tbMaisCompras.getModel();

        while (grid.getRowCount() > 0) {
            grid.removeRow(0);
        }

        try {
            int i = 0;
            while (i < c.List().size()) {

                Cliente cli = (Cliente) c.List().get(i);

                cli.setQtdCompra(c.quantidadeVendas(cli));

                grid.addRow(cli.carregarGridCompras());

                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void jButton_MAIS_DETALHES_MES1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MAIS_DETALHES_MES1ActionPerformed
        Cliente c = new Cliente();
        Cliente cli = new Cliente();
        int selecionada = tbMaisCompras.getSelectedRow();

        if (selecionada != -1) {

            String cpf = tbMaisCompras.getValueAt(selecionada, 2).toString();

            try {
                cli = c.findCliente(cpf);

                FrameMaisDetalhes frame = new FrameMaisDetalhes(cli);
                frame.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }

    }//GEN-LAST:event_jButton_MAIS_DETALHES_MES1ActionPerformed

    private void btnAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarActionPerformed
        Cliente c = new Cliente();
        Cliente cli = new Cliente();
        DefaultTableModel grid = (DefaultTableModel) tbMelhoresClientes.getModel();
        int selecionada = tbMelhoresClientes.getSelectedRow();

        if (selecionada != -1) {

            String cpf = tbMelhoresClientes.getValueAt(selecionada, 1).toString();
            String classificacao = tbMelhoresClientes.getValueAt(selecionada, 2).toString();

            try {

                cli = c.findCliente(cpf);

                if (classificacao.contains("1 - NOVO")) {
                    cli.setClassificacao("2 - REGULAR");
                    JOptionPane.showMessageDialog(this, "CLASSIFICAÇÃO ATUALIZADA");
                } else if (classificacao.contains("2 - REGULAR")) {
                    cli.setClassificacao("3 - IMPORTANTE");
                    JOptionPane.showMessageDialog(this, "CLASSIFICAÇÃO ATUALIZADA");
                } else if (classificacao.contains("3 - IMPORTANTE")) {
                    cli.setClassificacao("4 - MUITO IMPORTANTE");
                    JOptionPane.showMessageDialog(this, "CLASSIFICAÇÃO ATUALIZADA");
                } else if (classificacao.contains("4 - MUITO IMPORTANTE")) {
                    JOptionPane.showMessageDialog(this, "CLASSIFICAÇÃO NO MÁXIMO");

                }

                c.updateApenasCliente(cli);

                while (grid.getRowCount() > 0) {
                    grid.removeRow(0);
                }

                int i = 0;
                while (i < c.List().size()) {
                    Cliente clis = (Cliente) c.List().get(i);

                    grid.addRow(clis.carregarGrid());

                    i++;
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnAumentarActionPerformed

    private void btnDiminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiminuirActionPerformed
        Cliente c = new Cliente();
        Cliente cli = new Cliente();
        DefaultTableModel grid = (DefaultTableModel) tbMelhoresClientes.getModel();
        int selecionada = tbMelhoresClientes.getSelectedRow();

        if (selecionada != -1) {

            String cpf = tbMelhoresClientes.getValueAt(selecionada, 1).toString();
            String classificacao = tbMelhoresClientes.getValueAt(selecionada, 2).toString();

            try {

                cli = c.findCliente(cpf);

                if (classificacao.contains("1 - NOVO")) {
                    JOptionPane.showMessageDialog(this, "CLASSIFICAÇÃO NO MÍNIMO");
                } else if (classificacao.contains("2 - REGULAR")) {
                    cli.setClassificacao("1 - NOVO");
                    JOptionPane.showMessageDialog(this, "CLASSIFICAÇÃO ATUALIZADA");
                } else if (classificacao.contains("3 - IMPORTANTE")) {
                    cli.setClassificacao("2 - REGULAR");
                    JOptionPane.showMessageDialog(this, "CLASSIFICAÇÃO ATUALIZADA");
                } else if (classificacao.contains("4 - MUITO IMPORTANTE")) {
                    cli.setClassificacao("3 - IMPORTANTE");
                    JOptionPane.showMessageDialog(this, "CLASSIFICAÇÃO ATUALIZADA");

                }

                c.updateApenasCliente(cli);

                while (grid.getRowCount() > 0) {
                    grid.removeRow(0);
                }

                int i = 0;
                while (i < c.List().size()) {
                    Cliente clis = (Cliente) c.List().get(i);

                    grid.addRow(clis.carregarGrid());

                    i++;
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnDiminuirActionPerformed

    private void jButton_Alterar_nivel_mes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Alterar_nivel_mes1ActionPerformed
        Venda v = new Venda();
        Cliente cli = new Cliente();
        Cliente c = new Cliente();
        int selecionada = tbMaisCompras.getSelectedRow();

        if (selecionada != -1) {

            String  cpf= tbMaisCompras.getValueAt(selecionada, 2).toString();

            try {
                cli = c.findCliente(cpf);
                
                System.out.println(cli.getCodCliente());
                
                FrameHistoricoCompras frame = new FrameHistoricoCompras(cli);
                frame.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        
    }//GEN-LAST:event_jButton_Alterar_nivel_mes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Listar_Rank_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Listar_Rank_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Listar_Rank_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Listar_Rank_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Listar_Rank_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAumentar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnDiminuir;
    private javax.swing.JButton btnMaisDetalhes;
    private javax.swing.JButton jButton_Alterar_nivel_mes1;
    private javax.swing.JButton jButton_MAIS_DETALHES_MES1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_divisor_TOPO;
    private javax.swing.JPanel jPanel_guia_MelhoresClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane_RankClientes;
    private javax.swing.JTable tbMaisCompras;
    private javax.swing.JTable tbMelhoresClientes;
    // End of variables declaration//GEN-END:variables
}
