package package_frames_Desativados;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wellweb
 */
public class FrameDashBoard_Inutilizado extends javax.swing.JFrame {

    /**
     * Creates new form Frames_DashBoard
     */
    public FrameDashBoard_Inutilizado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_superior_blue = new javax.swing.JPanel();
        jButton_Icon_config = new javax.swing.JButton();
        jButton_icon_relatorios = new javax.swing.JButton();
        jButton_icon_Atualizacoes = new javax.swing.JButton();
        jButton_icon_Social = new javax.swing.JButton();
        jButton_icon_calendario = new javax.swing.JButton();
        jButton_icon_estrategia = new javax.swing.JButton();
        jButton_icon_faturamento = new javax.swing.JButton();
        jPanel_divisor_preto = new javax.swing.JPanel();
        jLabel_icon_config = new javax.swing.JLabel();
        jLabel_icon_CALENDARIO = new javax.swing.JLabel();
        jLabel_icon_Relatorios = new javax.swing.JLabel();
        jLabel_icon_Faturamento = new javax.swing.JLabel();
        jLabel_icon_Estrategia = new javax.swing.JLabel();
        jLabel_icon_SOCIAL = new javax.swing.JLabel();
        jLabel_icon_SOCIAL1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_icon_Clientes = new javax.swing.JButton();
        jLabel_icon_Clientes = new javax.swing.JLabel();
        jTabbedPane_Dashboard_principal_com_guias = new javax.swing.JTabbedPane();
        jPanel_guia_dashboard_page_relatorios = new javax.swing.JPanel();
        jPanel_divisor_guia_relatorios = new javax.swing.JPanel();
        jLabel_img_relatorios_on_guia_relatorios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_on_guia_Relatorios_DESENP = new javax.swing.JButton();
        jButton_on_guia_Relatorios_VENDAS = new javax.swing.JButton();
        jButton_on_guia_Relatorios_Social = new javax.swing.JButton();
        jButton_on_guia_Relatorios_SAC = new javax.swing.JButton();
        jPanel_taxa_crecimento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_mesReferencia = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_meses = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel_divisor_guia_marketing = new javax.swing.JPanel();
        jLabel_img_marketing = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_superior_blue.setBackground(new java.awt.Color(0, 153, 204));

        jButton_Icon_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/tools_1.png"))); // NOI18N

        jButton_icon_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/chart_up.png"))); // NOI18N

        jButton_icon_Atualizacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/refresh.png"))); // NOI18N

        jButton_icon_Social.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/monitor.png"))); // NOI18N

        jButton_icon_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/apple.png"))); // NOI18N
        jButton_icon_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_icon_calendarioActionPerformed(evt);
            }
        });

        jButton_icon_estrategia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/find.png"))); // NOI18N
        jButton_icon_estrategia.setPreferredSize(new java.awt.Dimension(89, 73));

        jButton_icon_faturamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/dollar_currency_sign.png"))); // NOI18N
        jButton_icon_faturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_icon_faturamentoActionPerformed(evt);
            }
        });

        jPanel_divisor_preto.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_preto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_divisor_pretoLayout = new javax.swing.GroupLayout(jPanel_divisor_preto);
        jPanel_divisor_preto.setLayout(jPanel_divisor_pretoLayout);
        jPanel_divisor_pretoLayout.setHorizontalGroup(
            jPanel_divisor_pretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_divisor_pretoLayout.setVerticalGroup(
            jPanel_divisor_pretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel_icon_config.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_config.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_config.setText("CONFIGURAÇÕES");

        jLabel_icon_CALENDARIO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_CALENDARIO.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_CALENDARIO.setText("PRODUTOS");

        jLabel_icon_Relatorios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_Relatorios.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_Relatorios.setText("RELATÓRIOS");

        jLabel_icon_Faturamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_Faturamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_Faturamento.setText("FATURAMENTO");

        jLabel_icon_Estrategia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_Estrategia.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_Estrategia.setText("ESTRATEGIA");

        jLabel_icon_SOCIAL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_SOCIAL.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_SOCIAL.setText("SOCIAL");

        jLabel_icon_SOCIAL1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_SOCIAL1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_SOCIAL1.setText("ATUALIZAÇÕES");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/by_Eramus7-watermark.png"))); // NOI18N

        jButton_icon_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/users.png"))); // NOI18N

        jLabel_icon_Clientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_icon_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_icon_Clientes.setText("CLIENTES");

        javax.swing.GroupLayout jPanel_superior_blueLayout = new javax.swing.GroupLayout(jPanel_superior_blue);
        jPanel_superior_blue.setLayout(jPanel_superior_blueLayout);
        jPanel_superior_blueLayout.setHorizontalGroup(
            jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_divisor_preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_icon_config)
                    .addComponent(jButton_Icon_config, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel_icon_CALENDARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton_icon_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel_icon_Relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton_icon_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel_icon_Faturamento))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton_icon_faturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel_icon_Estrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel_icon_SOCIAL))
                    .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton_icon_estrategia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButton_icon_Social, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel_icon_SOCIAL1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton_icon_Atualizacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_icon_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_icon_Clientes)))
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_superior_blueLayout.setVerticalGroup(
            jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_superior_blueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Icon_config, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jButton_icon_calendario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_icon_relatorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_icon_Atualizacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_icon_estrategia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_icon_Social, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_icon_faturamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_icon_Clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_superior_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_icon_config)
                    .addComponent(jLabel_icon_CALENDARIO)
                    .addComponent(jLabel_icon_Relatorios)
                    .addComponent(jLabel_icon_Faturamento)
                    .addComponent(jLabel_icon_SOCIAL1)
                    .addComponent(jLabel_icon_Estrategia)
                    .addComponent(jLabel_icon_SOCIAL)
                    .addComponent(jLabel_icon_Clientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel_divisor_preto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane_Dashboard_principal_com_guias.setBackground(new java.awt.Color(204, 255, 102));

        jPanel_guia_dashboard_page_relatorios.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_guia_dashboard_page_relatorios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel_divisor_guia_relatorios.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_guia_relatorios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_divisor_guia_relatoriosLayout = new javax.swing.GroupLayout(jPanel_divisor_guia_relatorios);
        jPanel_divisor_guia_relatorios.setLayout(jPanel_divisor_guia_relatoriosLayout);
        jPanel_divisor_guia_relatoriosLayout.setHorizontalGroup(
            jPanel_divisor_guia_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_divisor_guia_relatoriosLayout.setVerticalGroup(
            jPanel_divisor_guia_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jLabel_img_relatorios_on_guia_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/relatorios_dash.png"))); // NOI18N

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_on_guia_Relatorios_DESENP.setBackground(new java.awt.Color(51, 153, 255));
        jButton_on_guia_Relatorios_DESENP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_on_guia_Relatorios_DESENP.setForeground(new java.awt.Color(255, 255, 255));
        jButton_on_guia_Relatorios_DESENP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/chart_up_1.png"))); // NOI18N
        jButton_on_guia_Relatorios_DESENP.setText("Relatorio de Desempenho");

        jButton_on_guia_Relatorios_VENDAS.setBackground(new java.awt.Color(51, 153, 255));
        jButton_on_guia_Relatorios_VENDAS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_on_guia_Relatorios_VENDAS.setForeground(new java.awt.Color(255, 255, 255));
        jButton_on_guia_Relatorios_VENDAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/chart_up_1.png"))); // NOI18N
        jButton_on_guia_Relatorios_VENDAS.setText("Relatorio de Vendas");

        jButton_on_guia_Relatorios_Social.setBackground(new java.awt.Color(51, 153, 255));
        jButton_on_guia_Relatorios_Social.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_on_guia_Relatorios_Social.setForeground(new java.awt.Color(255, 255, 255));
        jButton_on_guia_Relatorios_Social.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/chart_up_1.png"))); // NOI18N
        jButton_on_guia_Relatorios_Social.setText("Relatorios Social");
        jButton_on_guia_Relatorios_Social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_on_guia_Relatorios_SocialActionPerformed(evt);
            }
        });

        jButton_on_guia_Relatorios_SAC.setBackground(new java.awt.Color(51, 153, 255));
        jButton_on_guia_Relatorios_SAC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_on_guia_Relatorios_SAC.setForeground(new java.awt.Color(255, 255, 255));
        jButton_on_guia_Relatorios_SAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/chart_up_1.png"))); // NOI18N
        jButton_on_guia_Relatorios_SAC.setText("Relatorios SAC");
        jButton_on_guia_Relatorios_SAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_on_guia_Relatorios_SACActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton_on_guia_Relatorios_DESENP)
                .addGap(44, 44, 44)
                .addComponent(jButton_on_guia_Relatorios_VENDAS)
                .addGap(48, 48, 48)
                .addComponent(jButton_on_guia_Relatorios_SAC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton_on_guia_Relatorios_Social)
                .addGap(173, 173, 173))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_on_guia_Relatorios_DESENP)
                    .addComponent(jButton_on_guia_Relatorios_VENDAS)
                    .addComponent(jButton_on_guia_Relatorios_SAC)
                    .addComponent(jButton_on_guia_Relatorios_Social))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel_taxa_crecimento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("MÊS DE REFERENCIA");

        jLabel_mesReferencia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("GERAR RELATÓRIO");

        jLabel4.setText("Alterar Mês : ");

        jComboBox_meses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox_meses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_mesesActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de Relatório :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VENDAS", "CLIENTES", "CONVERÇÃO", "CAPTAÇÃO", "RECLAMAÇÕES", "SOLUÇÕES", "SUGESTÕES", "MIDIA SOCIAL" }));

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("EXPORTAR");

        javax.swing.GroupLayout jPanel_taxa_crecimentoLayout = new javax.swing.GroupLayout(jPanel_taxa_crecimento);
        jPanel_taxa_crecimento.setLayout(jPanel_taxa_crecimentoLayout);
        jPanel_taxa_crecimentoLayout.setHorizontalGroup(
            jPanel_taxa_crecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_taxa_crecimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_taxa_crecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_mesReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel_taxa_crecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_meses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, 0, 141, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel_taxa_crecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel_taxa_crecimentoLayout.setVerticalGroup(
            jPanel_taxa_crecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_taxa_crecimentoLayout.createSequentialGroup()
                .addGroup(jPanel_taxa_crecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_taxa_crecimentoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_mesReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_taxa_crecimentoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_taxa_crecimentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel_guia_dashboard_page_relatoriosLayout = new javax.swing.GroupLayout(jPanel_guia_dashboard_page_relatorios);
        jPanel_guia_dashboard_page_relatorios.setLayout(jPanel_guia_dashboard_page_relatoriosLayout);
        jPanel_guia_dashboard_page_relatoriosLayout.setHorizontalGroup(
            jPanel_guia_dashboard_page_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_divisor_guia_relatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_guia_dashboard_page_relatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_taxa_crecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_img_relatorios_on_guia_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_guia_dashboard_page_relatoriosLayout.setVerticalGroup(
            jPanel_guia_dashboard_page_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_guia_dashboard_page_relatoriosLayout.createSequentialGroup()
                .addComponent(jPanel_divisor_guia_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_guia_dashboard_page_relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_img_relatorios_on_guia_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_taxa_crecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane_Dashboard_principal_com_guias.addTab("Relatórios", jPanel_guia_dashboard_page_relatorios);

        jPanel_divisor_guia_marketing.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_divisor_guia_marketing.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_divisor_guia_marketingLayout = new javax.swing.GroupLayout(jPanel_divisor_guia_marketing);
        jPanel_divisor_guia_marketing.setLayout(jPanel_divisor_guia_marketingLayout);
        jPanel_divisor_guia_marketingLayout.setHorizontalGroup(
            jPanel_divisor_guia_marketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        jPanel_divisor_guia_marketingLayout.setVerticalGroup(
            jPanel_divisor_guia_marketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jLabel_img_marketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/crm/Frames/br/imagens/marketing.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_divisor_guia_marketing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 1117, Short.MAX_VALUE)
                .addComponent(jLabel_img_marketing))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel_divisor_guia_marketing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_img_marketing)
                .addGap(0, 170, Short.MAX_VALUE))
        );

        jTabbedPane_Dashboard_principal_com_guias.addTab("Marketing", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_superior_blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_Dashboard_principal_com_guias)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_superior_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane_Dashboard_principal_com_guias, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_icon_calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_icon_calendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_icon_calendarioActionPerformed

    private void jButton_icon_faturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_icon_faturamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_icon_faturamentoActionPerformed

    private void jButton_on_guia_Relatorios_SocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_on_guia_Relatorios_SocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_on_guia_Relatorios_SocialActionPerformed

    private void jButton_on_guia_Relatorios_SACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_on_guia_Relatorios_SACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_on_guia_Relatorios_SACActionPerformed

    private void jComboBox_mesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_mesesActionPerformed
        jLabel_mesReferencia.setText(""+jComboBox_meses.getSelectedItem());
    }//GEN-LAST:event_jComboBox_mesesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDashBoard_Inutilizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDashBoard_Inutilizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDashBoard_Inutilizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDashBoard_Inutilizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDashBoard_Inutilizado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Icon_config;
    private javax.swing.JButton jButton_icon_Atualizacoes;
    private javax.swing.JButton jButton_icon_Clientes;
    private javax.swing.JButton jButton_icon_Social;
    private javax.swing.JButton jButton_icon_calendario;
    private javax.swing.JButton jButton_icon_estrategia;
    private javax.swing.JButton jButton_icon_faturamento;
    private javax.swing.JButton jButton_icon_relatorios;
    private javax.swing.JButton jButton_on_guia_Relatorios_DESENP;
    private javax.swing.JButton jButton_on_guia_Relatorios_SAC;
    private javax.swing.JButton jButton_on_guia_Relatorios_Social;
    private javax.swing.JButton jButton_on_guia_Relatorios_VENDAS;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox_meses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_icon_CALENDARIO;
    private javax.swing.JLabel jLabel_icon_Clientes;
    private javax.swing.JLabel jLabel_icon_Estrategia;
    private javax.swing.JLabel jLabel_icon_Faturamento;
    private javax.swing.JLabel jLabel_icon_Relatorios;
    private javax.swing.JLabel jLabel_icon_SOCIAL;
    private javax.swing.JLabel jLabel_icon_SOCIAL1;
    private javax.swing.JLabel jLabel_icon_config;
    private javax.swing.JLabel jLabel_img_marketing;
    private javax.swing.JLabel jLabel_img_relatorios_on_guia_relatorios;
    private javax.swing.JLabel jLabel_mesReferencia;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_divisor_guia_marketing;
    private javax.swing.JPanel jPanel_divisor_guia_relatorios;
    private javax.swing.JPanel jPanel_divisor_preto;
    private javax.swing.JPanel jPanel_guia_dashboard_page_relatorios;
    private javax.swing.JPanel jPanel_superior_blue;
    private javax.swing.JPanel jPanel_taxa_crecimento;
    private javax.swing.JTabbedPane jTabbedPane_Dashboard_principal_com_guias;
    // End of variables declaration//GEN-END:variables
}
